apiVersion: v2
name: code-search-website
description: A Helm chart for Code Search Website
type: application
version: "0.1.0"
appVersion: "latest"
keywords:
  - code-search
  - zoekt
  - search
  - developer-tools
maintainers:
  - name: André Nogueira
    url: https://github.com/techquestsdev
sources:
  - https://github.com/techquestsdev/code-search
icon: https://raw.githubusercontent.com/techquestsdev/code-search/refs/heads/main/deploy/helm/code-search-website/icon.svg
